# Generated by Django 3.2.22 on 2023-10-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='featured_image',
            new_name='profile_image',
        ),
    ]
