# Generated by Django 3.2.22 on 2023-10-27 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20231027_1325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SelectCategory',
            new_name='Variety',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='selectcategory',
            new_name='variety',
        ),
    ]
