# Generated by Django 3.2.22 on 2023-10-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20231027_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variety',
            options={'verbose_name_plural': 'varieties'},
        ),
    ]
