# Generated by Django 3.2.22 on 2023-10-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20231027_1720'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kind',
        ),
    ]
