# Generated by Django 3.2.22 on 2023-11-04 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='variety',
        ),
        migrations.AddField(
            model_name='post',
            name='varieties',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.SET_DEFAULT, to='home.variety'),
        ),
    ]
