# Generated by Django 3.2.22 on 2023-11-04 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20231104_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='varieties',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.SET_DEFAULT, to='home.variety'),
        ),
    ]
